[package]
name = "decryptable/satchel"
description = "A modern open-source alternative to Roblox's default backpack."
version = "1.5.1"
license = "MPL-2.0"
authors = ["Decryptable <hello@decryptable.dev>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
homepage = "http://satchel.decryptable.dev/"
repository = "https://github.com/decryptable/satchel"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE", "README.md"]

[dependencies]
topbarplus = "1foreverhd/topbarplus@3.4.0"
